version: '3'
services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - REACT_APP_API_URL=http://backend:8000

networks:
  mynetwork:
